on:
  pull_request:
  workflow_dispatch:

jobs:
  job-name:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Create PR review request
        env:
          GH_TOKEN: ${{github.token }}
        run: |
          pr_url="${{ github.event.pull_request.html_url }}"
          pr_number="${{ github.event.pull_request.number }}"
          echo "Requesting a review for PR #${pr_number} at ${pr_url}"
          gh api \
            --method POST \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            /repos/$GITHUB_REPOSITORY/pulls/$pr_number/requested_reviewers \
             -f "reviewers[]=stand-in-anth"
