on:
  pull_request:
  pull_request_target:

jobs:
  job-name:
    concurrency:
      group: recheck-$PR_NUMBER
      cancel-in-progress: true
    uses: anthmmatic/public-testbox/.github/workflows/reusewf.yml@anthms-patch-1
      
