name: Context
on:
  pull_request:
  #pull_request_target:

jobs:
  job-name:
    concurrency:
      group: recheck-${{ github.head_ref }}-to-${{ github.base_ref }}
      cancel-in-progress: true
    uses: anthmmatic/public-testbox/.github/workflows/reusewf.yml@v3
