on:
  pull_request:
  pull_request_target:

jobs:
  job-name:
    concurrency:
      group: recheck-${{ github.event.number }}
      cancel-in-progress: true
    runs-on: ubuntu-latest
    steps:
      - run: echo 'done'
      
